version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram_reverseproxy
    image: udagram_reverseproxy
  backend_user:
    build:
      context: ./udagram_user
    image: udagram_user
  backend_feed:
    build:
      context: ./udagram_feed
    image: udagram_feed
  frontend:
    build:
      context: ./udagram_frontend
    image: udagram_frontend